### PR TITLE
Correct misspelling // Fix lexicon-loading

### PR DESCRIPTION
**Pull request by sebastian-marinescu**
Fixes loading the lexicon

### CODE REVIEW

**Comment by sebastian-marinescu** [comment]
@BobRay What's holding you up? :)

**Comment by Jako** [comment]
Nice find!

**Comment by sebastian-marinescu** [comment]
Thanks @Jako 
Just wanted to get rid of the error message :)

**Comment by BobRay** [comment]
Merged manually. Sorry about the delay, I just found out today that my GitHub notifications have been broken for a very long time.

**Pull request closed without merging**
