### PR TITLE
Adding french translation

### PR DESCRIPTION
**Pull request by intersel**
Hi Bob
Romain Tripault had left a message on slack that you would need french translation on this...
Hoping it is still needed... there it is...
1st version that surely needs to be reviewed by other french guys as I don't have all the context...

### CODE REVIEW

**Comment by BobRay** [comment]
Hi intersel,

Thanks! I'm afraid Philippe Delberghe (AmaZili) sent me a finished French translation a little ahead of yours.  I'm sorry about not being able to use yours, but I sure appreciate the effort. Please put out the word that it's done.

Bob

**Comment by intersel** [comment]
Hi Bob,
no pb... AMazili told me... I put out the word ...

**Comment by BobRay** [comment]
Hi intersel,

Hi Sebastian,

I'm getting ready to release UpgradeMODX 2.0.0-pl very soon. Since the core team expressed an interest in putting UpgradeMODX into the core of MODX 3,  I ended up doing everything with processors and moving all the snippet properties to System Settings. I needed to create some new lexicon strings so there are more to translate. I think I've put all the new ones and their English versions at the end of the default language file.

If you have time to translate the new strings, that would be great. If not, I'll just leave those in English and update the files later.

I really appreciate your translation help and I'm sure others will too.

Cheers,

Bob

**Comment by intersel** [comment]
Hi Bob, not sure I can have a look on it before next week or the one after...  :-s

**Pull request closed without merging**
