### PR TITLE
Translate new strings for German-Language and fix some other lexica

### PR DESCRIPTION
**Pull request by sebastian-marinescu**
Hi @BobRay, like promised, I looked over the translations and did my best 👍 
If you need anything else, let me know.

### CODE REVIEW

**Comment by sebastian-marinescu** [comment]
Hi @BobRay I think we were talking in the wrong PR :laughing:

**Comment by sebastian-marinescu** [comment]
Hi @BobRay, I've fixed some things back. And all the strings are translated in German. 
The PR is ready to be merged!

**Comment by BobRay** [comment]
Thanks Sebastian!

I've had to paste it manually because I'm working in another local branch, where I've had to revert some things, so you won't see it in the dev branch for a while.

**Comment by sebastian-marinescu** [comment]
You're welcome Bob! :)

**Comment by BobRay** [comment]
Hi Sebastian,

I'm getting ready to release UpgradeMODX 2.0.0-pl very soon. Since the core
team expressed an interest in putting UpgradeMODX into the core of MODX 3,
I ended up doing everything with processors and moving all the snippet
properties to System Settings. I needed to create some new lexicon strings
so there are more to translate. I think I've put all the new ones and their
English versions at the end of the default language file.

If you have time to translate the new strings, that would be great. If not,
I'll just leave those in English and update the files later.

I really appreciate your translation help and I'm sure others will too.

Cheers,

Bob

**Pull request closed without merging**
